#!/usr/bin/python3
# -*- coding: utf-8
#+
# Given n positive integers, try to use any combination of integer addition, subtraction,
# multiplication and division to try to come up with a specified result. Invoke this
# script as follows:
#
#     make_answer n1 n2 n3 ... target
#
# where the arguments are sequence of positive integers, the last one being the target
# value to achieve, and the others being the operands to use to produce that answer.
# The output will be the possible solutions, one to a line.
#
# Written by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
#-

import sys

def permute(seq) :
    "generator which yields successive distinctive permutations of the elements of seq." \
    " Correctly skips duplicate permutations of duplicate elements."

    def do_permute(seq) :
        if len(seq) == 0 :
            yield ()
        else :
            prev = None
            for i in range(0, len(seq)) :
                if seq[i] != prev :
                    for rest in permute(seq[:i] + seq[i + 1:]) :
                        yield (seq[i],) + rest
                    #end for
                #end if
                prev = seq[i]
            #end for
        #end if
     #end do_permute

#begin permute
    return do_permute(sorted(seq))
#end permute

class Expr :
    "represents an expression."

    def __init__(self, op, a, b) :
        self.op = op
        self.a = a
        self.b = b
    #end __init__

    def eval(self) :
        "returns the value of the expression as a tuple of 2 values, the second" \
        " being an indication of validity."
        return self.op.func(self.a, self.b)
    #end eval

    def display(self) :
        "returns a formatted represention of the expression."
        return "(" + self.a.display() + " " + self.op.display() + " " + self.b.display() + ")"
    #end display

#end Expr

class Num :
    "represents a single number."

    def __init__(self, val) :
        self.val = val
    #end __init__

    def eval(self) :
        "returns the value of the number as a tuple of 2 values, the second" \
        " being an indication of validity (always True)."
        return self.val, True
    #end eval

    def display(self) :
        "returns a formatted represention of the number."
        return str(self.val)
    #end display

#end Num

class Op :
    "constructs an operator."

    def __init__(self, name, func) :
        self.name = name
        self.func = func
    #end __init__

    def construct(self, a, b) :
        "constructs an expression using the operator and the specified operands."
        return Expr(self, a, b)
    #end construct

    def display(self) :
        "returns a formatted represention of the operator applied to its operands."
        return self.name
    #end display

#end Op

def add(a, b) :
    "addition operation, always valid if operands are valid."
    a = a.eval()
    b = b.eval()
    return a[0] + b[0], a[1] and b[1]
#end add

def sub(a, b) :
    "subtraction operation, valid if operands are valid and" \
    " first operand is not less than second."
    a = a.eval()
    b = b.eval()
    return a[0] - b[0], a[1] and b[1] and a[0] >= b[0]
#end sub

def mul(a, b) :
    "addition operation, always valid if operands are valid."
    a = a.eval()
    b = b.eval()
    return a[0] * b[0], a[1] and b[1]
#end mul

def intdiv(a, b) :
    "division operation, valid if operands are valid and" \
    " second operand is not zero and first operand is exactly divisible by second."
    a = a.eval()
    b = b.eval()
    return a[0] // b[0] if b[0] != 0 else 0, a[1] and b[1] and b[0] != 0 and a[0] % b[0] == 0
#end intdiv

operators = \
    ( # list of all the valid operators
        Op("+", add),
        Op("-", sub),
        Op("×", mul),
        Op("÷", intdiv),
    )

def choose_ops(nr) :
    "generator which yields all combinations of the specified number of operators."
    if nr == 0 :
        yield ()
    else :
        for rest in choose_ops(nr - 1) :
            for op in operators :
                yield (op,) + rest
            #end for
        #end for
    #end if
#end choose_ops

#+
# Mainline
#-

numbers = tuple(int(n) for n in sys.argv[1:])
target = numbers[-1]
numbers = numbers[:-1]

nr_answers = 0
for perm in permute(numbers) :
    for op_choice in choose_ops(len(numbers) - 1) :
        expr = Num(perm[0])
        for i in range(1, len(perm)) :
            expr = op_choice[i - 1].construct(expr, Num(perm[i]))
        #end for
        val, ok = expr.eval()
        if ok and val == target :
            nr_answers += 1
            sys.stdout.write("%d: %s = %d\n" % (nr_answers, expr.display(), target))
        #end if
    #end for
#end for
if nr_answers == 0 :
    sys.stdout.write("No answers found\n")
#end if
